-- craeting table
CREATE TABLE CUSTOMER (
	CUSTOMER_NO CHAR (5) PRIMARY KEY ,
	CUSTOMER_NAME VARCHAR (20) NOT NULL ,
	CUSTOMER_CITY VARCHAR (10)
) ;

CREATE TABLE ACCOUNT (
	ACCOUNT_NO CHAR (5) PRIMARY KEY ,
	BALANCE DECIMAL (12 ,2) NOT NULL
) ;

CREATE TABLE DEPOSITOR (
	CUSTOMER_NO CHAR (5) ,
	ACCOUNT_NO CHAR (5) ,
	PRIMARY KEY ( CUSTOMER_NO , ACCOUNT_NO )
) ;

INSERT INTO CUSTOMER ( CUSTOMER_NO , CUSTOMER_NAME , CUSTOMER_CITY ) VALUES
("C-101", "John Doe", "DHK") ;
INSERT INTO CUSTOMER ( CUSTOMER_NO , CUSTOMER_NAME , CUSTOMER_CITY ) VALUES 
("C-102 ", "Jane Smith", "KHL") ;
INSERT INTO CUSTOMER ( CUSTOMER_NO , CUSTOMER_NAME , CUSTOMER_CITY ) VALUES 
("C-103", "Alice Brown", "CTG") ;
INSERT INTO CUSTOMER ( CUSTOMER_NO , CUSTOMER_NAME , CUSTOMER_CITY ) VALUES 
("C-104", "Bob Johnson", "DHK") ;

INSERT INTO ACCOUNT ( ACCOUNT_NO , BALANCE ) VALUES
("A-101", 5000.00) ;
INSERT INTO ACCOUNT (  ACCOUNT_NO , BALANCE  ) VALUES 
("A-102", 15000.00) ;
INSERT INTO ACCOUNT (  ACCOUNT_NO , BALANCE  ) VALUES 
("A-103", 25000.00) ;
INSERT INTO ACCOUNT ( ACCOUNT_NO , BALANCE  ) VALUES 
("A-104", 8000.00) ;

INSERT INTO DEPOSITOR ( CUSTOMER_NO , ACCOUNT_NO ) VALUES 
("C-101", "A-101"),
("C-102", "A-102"),
("C-103", "A-103"),
("C-104", "A-104") ;

-- 					TASK-1					--

-- 1
ALTER TABLE CUSTOMER ADD COLUMN DATE_OF_BIRTH DATE;
-- 2
RENAME TABLE DEPOSITOR TO DEPOSITOR_INFO; 
-- 3 
ALTER TABLE DEPOSITOR_INFO
CHANGE COLUMN ACCOUNT_NO A_NO CHAR (5) ,
CHANGE COLUMN CUSTOMER_NO C_NO CHAR (5) ;
-- 4
ALTER TABLE DEPOSITOR_INFO ADD CONSTRAINT FK_DEPOSITOR_ACCOUNT
FOREIGN KEY (A_NO) REFERENCES ACCOUNT(ACCOUNT_NO)
ON DELETE CASCADE
ON UPDATE CASCADE;

ALTER TABLE DEPOSITOR_INFO ADD CONSTRAINT FK_DEPOSITOR_CUSTOMER
FOREIGN KEY (C_NO) REFERENCES CUSTOMER(CUSTOMER_NO)
ON DELETE CASCADE
ON UPDATE CASCADE;

-- 5
SELECT *
FROM CUSTOMER;

-- 6
SELECT C.CUSTOMER_NAME, A.BALANCE
FROM CUSTOMER C
INNER JOIN DEPOSITOR_INFO D ON C.CUSTOMER_NO = D.C_NO
INNER JOIN ACCOUNT A ON D.A_NO = A.ACCOUNT_NO;

-- 7
SELECT AVG(balance)
FROM ACCOUNT;

-- 8
SELECT CUSTOMER_NAME, A_NO
FROM CUSTOMER
NATURAL JOIN DEPOSITOR_INFO;

-- 9
UPDATE CUSTOMER
SET CUSTOMER_CITY = "KLN"
WHERE CUSTOMER_NO = "C-102";

-- 10
DELETE FROM ACCOUNT
WHERE ACCOUNT_NO = "A-104";

-- 11
DELETE FROM CUSTOMER 
WHERE CUSTOMER_NO NOT IN (
SELECT C_NO FROM DEPOSITOR_INFO);