-- 1
CREATE TABLE LOAN(
	LOAN_NO CHAR(5) PRIMARY KEY,
    AMOUNT DECIMAL(12, 2) NOT NULL
);

INSERT INTO LOAN (LOAN_NO, AMOUNT) VALUES
("L-201", 10000.00),
("L-202", 20000.00),
("L-203", 15000.00);

-- 2
CREATE TABLE BORROWER (
	CUSTOMER_NO CHAR(5),
    LOAN_NO CHAR(5),
    PRIMARY KEY (CUSTOMER_NO, LOAN_NO),
    FOREIGN KEY (CUSTOMER_NO) REFERENCES CUSTOMER(CUSTOMER_NO),
    FOREIGN KEY (LOAN_NO) REFERENCES LOAN(LOAN_NO)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);

INSERT INTO BORROWER (CUSTOMER_NO, LOAN_NO) VALUES 
("C-101", "L-201"),
("C-102", "L-202"),
("C-103", "L-203");

-- 3
SELECT * 
FROM CUSTOMER C
INNER JOIN BORROWER B ON C.CUSTOMER_NO = B.CUSTOMER_NO;

-- 4
SELECT *
FROM CUSTOMER 
WHERE CUSTOMER_NO NOT IN
(SELECT CUSTOMER_NO FROM BORROWER);

-- 5
UPDATE ACCOUNT
SET BALANCE = BALANCE + BALANCE*0.5
WHERE BALANCE < 10000;
